### ISSUE TITLE
Allow Behance.net as a link

### ISSUE THREAD

**Issue by pixelflowxyz** [megaxlr/Xisuma-Sub4sub#1]
Hey there Mega.
I'm in the Xisumaverse Discord, and I noticed that Sub4Sub does not allow Behance.net as a link.
Behance is the world's largest graphic design community, and is like YouTube, but for graphic design.
Owned by Adobe, it is moderated well and I would love to see this allowed.
Thanks,
pixelflow#2332 aka Dan.

**Comment by megaxlr** [comment]
Sounds like a good idea. 
I dont use behance myself, I dont know their URL format.

Can you send me a set of test URLs so I can write the checks for them?
